name: Export Unknown Wiki List for LLM

on:
  schedule:
    # 00:00 JST every weekday
    # ⚠️ The timing is somehow not accurate at all
    - cron: "0 15 * * 1-5"
  workflow_dispatch:
    inputs:
      group_by:
        description: "Specify the grouping criteria for the wiki pages"
        required: true
        default: Owner
        type: choice
        options:
          - Owner
          - Category
      language:
        description: "Specify the language used for the wiki pages"
        required: true
        default: English
        type: choice
        options:
          - English
          - Japanese

permissions:
  contents: write

jobs:
  export:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      commit_message: ${{ steps.commit.outputs.commit_message }}
      jst_current_datetime: ${{ steps.commit.outputs.jst_current_datetime }}
    steps:
      - name: Checkout the Main Repository
        uses: actions/checkout@v7
        with:
          repository: "${{ github.repository }}"
          ref: master
          path: ./github-wiki-organisers
      - name: Checkout the Wiki Repository
        uses: actions/checkout@v7
        with:
          repository: "${{ github.repository }}.wiki"
          ref: master
          path: ./github-wiki-organisers/wiki
      - name: Configure Git Identity
        uses: ./github-wiki-organisers/.github/actions/configure-git-identity
      - uses: ./github-wiki-organisers/.github/actions/setup-ruby
      - name: Export Unknown Wiki List for LLM
        working-directory: ./github-wiki-organisers/wiki
        run: |
          set -xe
          git pull origin master
          bash export_unknown_wiki_list_for_llm.sh "${{ github.event.inputs.group_by || 'Owner' }}" "${{ github.event.inputs.language || 'English' }}"
      - name: Commit and Push
        id: commit
        uses: ./github-wiki-organisers/.github/actions/commit-and-push
        with:
          working-directory: ./github-wiki-organisers/wiki
          commit-message-prefix: "Commit unknown_wiki_list_for_llm.txt by GitHub Actions[bot]"

  notify:
    needs: export
    if: contains(needs.export.outputs.commit_message, needs.export.outputs.jst_current_datetime)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Main Repository
        uses: actions/checkout@v7
      - name: Slack Notification
        uses: ./.github/actions/slack-notify
        with:
          slack-token: ${{ secrets.SLACK_APP_TOKEN }}
          slack-channel: ${{ secrets.SLACK_CHANNEL_ID }}
          header: "【github-wiki-organisers Wiki LLM Notification for Ignored Page List Export】"
          mrkdwn-sections: |
            Message: The latest ignored page list for LLM has been exported! Make sure if it is as you expect by cloning ${{ github.repository }}.wiki !
            Workflows: <https://github.com/${{ github.repository }}/actions/workflows/export-unknown-wiki-list-for-llm.yml|Export Unknown Wiki List for LLM>
